### ISSUE TITLE
censusIndCode2010: insufficient information means missing, no?

### ISSUE THREAD

**Issue by dckc** [WerthPADOH/naaccr#36]
This looks suspect:

```tsv
code 	label 	means_missing 	description
9990 	insufficient information 	FALSE 	insufficient information
```

https://github.com/WerthPADOH/naaccr/blob/master/data-raw/code-labels/censusIndCode2010.csv#L273

**Comment by WerthPADOH** [comment]
Nice catch!  Didn't expect them to end an "unknown" code with something other than 8 or 9.

Fixed in 5265acf
