### ISSUE TITLE
no code scheme for 430 behaviorIcdO2?

### ISSUE THREAD

**Issue by dckc** [WerthPADOH/naaccr#39]
I see you have it as `type = 'character'` with no code labels. Is this because you haven't used this item much?
https://github.com/WerthPADOH/naaccr/blob/master/data-raw/field_info.csv#L86

LOINC answer list LL212-2 (component 21857-8) has:

answer_code | | answer_string
-- | -- | --
1 |   | Grade I
2 |   | Grade II
3 |   | Grade III
4 |   | Grade IV
5 |   | T-cell
6 |   | B-cell
7 |   | Null cell
8 |   | NK (natural killer) cell
9 |   | Grade/differentiation unknown, not stated, or not applicable

LOINC gave me permission to include this in my work.
https://github.com/kumc-bmi/naaccr-tumor-data/blob/loinc-csvdb/loinc-naaccr/LOINC_NOTICE.md
https://github.com/kumc-bmi/naaccr-tumor-data/blob/loinc-csvdb/loinc-naaccr/loinc_naaccr_answer.csv

**Comment by WerthPADOH** [comment]
Thanks for pointing this out.  A lot of the code files came from rough drafts made with a script, so I'm not surprised one was missing.

By the way, you posted a code table for [grade](http://datadictionary.naaccr.org/default.aspx?c=10#440) instead of behavior.

**Comment by dckc** [comment]
I posted what's in LOINC, I'm pretty sure. I guess the NAACCR LOINC mapping is iffy.
