### ISSUE TITLE
Add XML-handling to read_naaccr

### ISSUE THREAD

**Issue by WerthPADOH** [WerthPADOH/naaccr#6]

**Comment by dckc** [comment]
Have you seen https://github.com/imsweb/naaccr-xml ?

**Comment by WerthPADOH** [comment]
That's where I took the v18 items from:

https://github.com/WerthPADOH/naaccr/blob/4416f67f213688c5512237a438576f82c1a5dab9/ignore/create-record-format-files.R#L3

I'm not familiar with Java, so I don't know if anything else could be pulled from that repo.

**Comment by dckc** [comment]
(For anyone else following along...) If you're interested in quick-and-dirty, you could use RJava... or just system.

But I don't see any such expedient hacks elsewhere in this project, so I can understand why you wouldn't take that approach.

**Comment by WerthPADOH** [comment]
Addressed with commit ac4bab570001e24da97ff3ba912746dbc7f7e843
