### ISSUE TITLE
code-labels are not unique - by design?

### ISSUE THREAD

**Issue by dckc** [WerthPADOH/naaccr#73]
I just discovered that NE is mapped to both Nebraska and Northeast in state.csv. Is this by design? I don't understand how this would work as an R factor.

https://github.com/WerthPADOH/naaccr/blob/master/data-raw/code-labels/state.csv

**Comment by WerthPADOH** [comment]
Thanks for catching this!
I wasn't careful enough checking the values when I scraped these codes from an official file.
I can't even remember what the official file was.
